### ISSUE TITLE
Part 1

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#1]
Finish Part 1 Exercices

**Comment by kyweez** [comment]
## Part 1 done !
Peux tu regarder et me conseiller ? Qu'est-ce que je peux améliorer ?
J'ai amélioré les consignes pour certains exo afin de mettre un peu plus de difficultés.
L'exercice 1.10v0 met énormément de temps quand N >=5 Je ne sais pas trop comment optimiser.

**Comment by mdevoldere** [comment]
Les raisonnement est OK :) Les 32M d'itérations ne plaisent ni à java, ni au cpu :)
