### ISSUE TITLE
Exercices UML 200615

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#13]
Soit les phrases suivantes :

• Un répertoire contient des fichiers
• Une pièce contient des murs
• Les modems et claviers sont des périphériques d’entrée / sortie
• Une transaction boursière est un achat ou une vente
• Un compte bancaire peut appartenir à une personne physique ou morale

Élaborez les diagrammes de classe correspondants en choisissant le type de relation approprié

**Comment by kyweez** [comment]
# Exercices UML 200615 (mail)
Exercices finis. Peux-tu me faire un retour stp ?

**Comment by mdevoldere** [comment]
BankAccount : L'association relie directement la classe parente 🔍 
Répertoire : OK pour la version "humain" 👍
