### ISSUE TITLE
Algo-Part 2

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#2]
Finish Part 2 Exercices

**Comment by kyweez** [comment]
### Partie 2 de la page d'exercices terminée. 
Peux-tu faire le tour des exercices et me faire un retour s'il te plait ? Que puis-je améliorer ? Que dois-je éviter à tout prix ?
Le début est en Java, la fin en JS. (L'exercice trop verbeux, je l'ai fait sur Enterprise Architect (une version PNG est dispo)

**Comment by mdevoldere** [comment]
2 erreurs se sont glissées dans le diagramme EA pour la bicyclette. Un indice: "J'aimerais bien lire GoT si je le possède !" 👯

**Comment by mdevoldere** [comment]
latence cérébrale :)
