### ISSUE TITLE
Algo-Part 3

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#3]
Finish Part 3 Exercices

**Comment by kyweez** [comment]
### Partie 3 finie
Ce sont des gros exercices pour la plupart, qui peuvent être indigestes à lire. J'ai essayé de moduler au mieux pour que ce soit plus facile à lire.

Pour le pendu (3.6), beaucoup de lignes sont attribuées malheureusement au display et aux gestion d'input user. Je te conseille de le lancer avant de regarder le code, c'est rigolo !

Pour le 3.7 : Ce n’était pas demandé, mais j'ai rajouté un "fs module" pour lire les prénoms d'un fichier texte rempli sur une colonne. J'ai aussi fait un "merge sort" qui est le 5e algo de tri que je code sur toute cette série d'exos. Ça fait du bien de faire tout ces exercices, j'ai beaucoup appris.

**Comment by mdevoldere** [comment]
Comme d'hab, RaS :D
