### ISSUE TITLE
JS-00 - Employees TP

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#4]
Exercice à finir pour le mercredi 27/05/20

**Comment by kyweez** [comment]
Bonjour Mickael, 
J'ai fini l'exercice, le voici pour correction. J'ai restructuré un peu le document et mis les consignes en dehors sur un fichier texte. De même pour des raisons de lisibilité du code, je me suis permis de supprimer la zone non éditable. En revanche, toutes les fonctions qui y figuraient sont présentes et non-modifiées ! Je peux encore optimiser, mais j'ai utiliser beaucoup de nouvelles notions pour moi, je pense que c'est déjà pas mal.
Bonne correction !

**Comment by mdevoldere** [comment]
Bon boulot, bien structuré. (j'ai quand même réussi à le faire planter hihi :)
