### ISSUE TITLE
Web-00 - Site web Flexbox card layout

### ISSUE THREAD

**Issue by kyweez** [kyweez/CDA-01-Java-JS#5]
Réaliser l'interface HTML suivante :
https://gyazo.com/ae21588b4a2f244e681c5f1b78de6e0c

- Vous devez respecter les couleurs, la taille et la position des éléments
- Le choix des photos vous appartient
- Javascript interdit

**Comment by kyweez** [comment]
### Site Web fini
Réalisation du site web comme demandé. Valide au W3C. CSS OK et responsive. Peux tu me faire un retour sur les choses à améliorer stp ?

**Comment by mdevoldere** [comment]
Le CSS est OK (toutefois auj, on est plus sur une approche mobile-first). Pour les petites astuces, en vocal :)
